// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuF8j_IxuSsbT-val1opGNha38znccCw',
    appId: '1:519833620836:web:c6cff6254eeb8f0cdfea71',
    messagingSenderId: '519833620836',
    projectId: 'testing-3b97c',
    authDomain: 'testing-3b97c.firebaseapp.com',
    databaseURL: 'https://testing-3b97c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-3b97c.firebasestorage.app',
    measurementId: 'G-PJNVDGXJ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVba8kxZaDwAvhmApPZiVvTb-IBah2-ms',
    appId: '1:519833620836:android:91fb0b50031f691fdfea71',
    messagingSenderId: '519833620836',
    projectId: 'testing-3b97c',
    databaseURL: 'https://testing-3b97c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-3b97c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOOjtv5_lFuuc0KpiHoHZo6o0gWIWHS4',
    appId: '1:519833620836:ios:e454b252a1bc9195dfea71',
    messagingSenderId: '519833620836',
    projectId: 'testing-3b97c',
    databaseURL: 'https://testing-3b97c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-3b97c.firebasestorage.app',
    iosBundleId: 'com.example.paaModul6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOOjtv5_lFuuc0KpiHoHZo6o0gWIWHS4',
    appId: '1:519833620836:ios:e454b252a1bc9195dfea71',
    messagingSenderId: '519833620836',
    projectId: 'testing-3b97c',
    databaseURL: 'https://testing-3b97c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-3b97c.firebasestorage.app',
    iosBundleId: 'com.example.paaModul6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmuF8j_IxuSsbT-val1opGNha38znccCw',
    appId: '1:519833620836:web:7449f2348ad35a31dfea71',
    messagingSenderId: '519833620836',
    projectId: 'testing-3b97c',
    authDomain: 'testing-3b97c.firebaseapp.com',
    databaseURL: 'https://testing-3b97c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-3b97c.firebasestorage.app',
    measurementId: 'G-Y9M7F3T5M4',
  );

}